import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider } from '../context/AuthContext';
import { ProtectedRoute } from './ProtectedRoute';
import { LandingPage } from '../pages/LandingPage';
import { LoginPage } from '../pages/LoginPage';
import { RegisterPage } from '../pages/RegisterPage';
import { OTPVerificationPage } from '../pages/OTPVerificationPage';
import { ForgotPasswordPage } from '../pages/ForgotPasswordPage';
import { DashboardPage } from '../pages/DashboardPage';
import { ResumeAnalyzerPage } from '../pages/ResumeAnalyzerPage';
import { SkillGapPage } from '../pages/SkillGapPage';
import { CareerPathsPage } from '../pages/CareerPathsPage';
import { RoadmapPage } from '../pages/RoadmapPage';
import { MentorChatPage } from '../pages/MentorChatPage';
import { UserPage } from '../pages/UserPage';
import { SettingsPage } from '../pages/SettingsPage';
export const AppRoutes = () => {
    return (_jsx(Router, { children: _jsx(AuthProvider, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(LandingPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/otp-verification", element: _jsx(OTPVerificationPage, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPasswordPage, {}) }), _jsx(Route, { path: "/dashboard", element: _jsx(ProtectedRoute, { children: _jsx(DashboardPage, {}) }) }), _jsx(Route, { path: "/resume-analyzer", element: _jsx(ProtectedRoute, { children: _jsx(ResumeAnalyzerPage, {}) }) }), _jsx(Route, { path: "/skill-gap", element: _jsx(ProtectedRoute, { children: _jsx(SkillGapPage, {}) }) }), _jsx(Route, { path: "/career-paths", element: _jsx(ProtectedRoute, { children: _jsx(CareerPathsPage, {}) }) }), _jsx(Route, { path: "/roadmap/:id", element: _jsx(ProtectedRoute, { children: _jsx(RoadmapPage, {}) }) }), _jsx(Route, { path: "/roadmap", element: _jsx(ProtectedRoute, { children: _jsx(RoadmapPage, {}) }) }), _jsx(Route, { path: "/mentor-chat", element: _jsx(ProtectedRoute, { children: _jsx(MentorChatPage, {}) }) }), _jsx(Route, { path: "/profile", element: _jsx(ProtectedRoute, { children: _jsx(UserPage, {}) }) }), _jsx(Route, { path: "/settings", element: _jsx(ProtectedRoute, { children: _jsx(SettingsPage, {}) }) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }) }));
};
